name: trivy

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  trivy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        id: build
        run: |
          IMAGE=test/crabinfo:${GITHUB_SHA}
          docker build -t ${IMAGE} .
          echo "::set-output name=image::$IMAGE"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

          trivy-config: trivy.yml

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'